export const GROUP_ORDER_ACTIONS = {
  START_SESSION: 'START_SESSION',
  SET_PARTICIPANTS: 'SET_PARTICIPANTS',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  UPDATE_QTY: 'UPDATE_QTY',
  SET_PAYMENT_STATUS: 'SET_PAYMENT_STATUS',
  RESET: 'RESET',
};